services:
  pgdb:
    image: postgres:18.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comandadb
    volumes:
      - pgdata_new:/var/lib/postgresql/data
    networks:
      - comandas_net

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@pgdb:5432/comandadb
    networks:
      - comandas_net
    depends_on:
      - pgdb

networks:
  comandas_net:
    driver: bridge

volumes:
  pgdata_new:
